name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy dist to root
        run: |
          cp -r dist/* ./
          rm -rf dist
          git config --global user.name "Vinilka"
          git config --global user.email "you@example.com"
          git add .
          git commit -m "Auto-deploy via GitHub Actions" || echo "No changes"
          git push
